In [1]:
import numpy as np

Numpy arrays essentially come in two flavors: Vectors and matrices.
Vectors are strictly 1-d arrays and matrices are 2-d.
Matrix can still have only one row or one column.

#### NumPy Arrays

In [6]:
arr = np.array([1,2,3])

In [7]:
arr

array([1, 2, 3])

In [15]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Most common way of creating an array using Numpy is arrange method.
It is faster than creating array with previous method.

In [18]:
np.arange(0,10)  # One dimensional array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,11,2)  # Only even numbers 

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(10)   #create an array of length 10 with all zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
# Zero matrix or null matrix
np.zeros((5,5))  #Create 5X5 matrix with all zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [24]:
np.ones(3)

array([1., 1., 1.])

In [25]:
#Unit Matrix - Matrix which contains all ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
#Return evenly spaced numbers over a specified interval.
# We have to provide start, end and the no. of points we want
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [30]:
#Identity Matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Random Function 

In [32]:
#Create array of random numbers
#Returns a 1-d array of 10 numbers between 0-1
np.random.rand(10)  

array([0.80483287, 0.80945223, 0.33473884, 0.52669876, 0.26864656,
       0.50727754, 0.30600601, 0.83397585, 0.69072835, 0.16685705])

In [40]:
#Returns a 2-d(Matrix) array of 10 numbers between 0-1
np.random.rand(5,5)

array([[0.24016564, 0.76860699, 0.06582777, 0.80198747, 0.47594103],
       [0.71678688, 0.49717029, 0.18256799, 0.07236831, 0.52084925],
       [0.21956746, 0.29040926, 0.12166017, 0.27303392, 0.91088563],
       [0.51775412, 0.23859639, 0.26395524, 0.1022394 , 0.29822153],
       [0.41867808, 0.25780928, 0.05645171, 0.13544877, 0.47210336]])

In [41]:
# Getting data from standard distribution or Gussian distribution
np.random.randn(4)

array([ 1.24822234, -0.0622889 ,  0.34756999,  0.54210198])

In [42]:
np.random.randn(4,4)

array([[-1.35014555, -0.33206198, -0.90901648,  0.60712544],
       [ 0.61117754, -1.06777037, -0.22550794,  0.57745324],
       [-1.19727838,  0.14168176,  1.26444281, -0.80882828],
       [-1.90280299, -0.98678425,  1.5587005 ,  1.55974474]])

In [96]:
#Get array of 10 random number between 0 to 100
np.random.randint(1,100,10)

array([ 5, 17, 17,  1, 31, 91, 52, 94, 22, 30])

In [97]:
arr = np.arange(25)

In [98]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [108]:
ranarr = np.random.randint(0,50,10)

In [109]:
ranarr

array([21, 35, 46, 44, 18, 19, 32, 11,  2, 38])

In [114]:
#Reshaping an array
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [110]:
print(ranarr.argmax())  #Index location of Maximum value
print(ranarr.argmin()) #Index location of Minimum value

2
8


In [112]:
ranarr.shape # Shape of the array

(10,)

In [116]:
ranarr.dtype  #Get details of data-type of elements available

dtype('int32')

#### NumPy - Indexing and Selection - 1-D Array

In [145]:
arr = np.arange(0,11)

In [146]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
arr[8]

8

In [148]:
arr[0:5]  #Same as List

array([0, 1, 2, 3, 4])

In [149]:
arr[:5]

array([0, 1, 2, 3, 4])

In [150]:
arr[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Broadcast a value into a Python array

In [151]:
arr[0:5] = 100 # This will set all the elements from 0-5 as 100

In [152]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [153]:
slice_of_arr = arr[0:6]

In [137]:
slice_of_arr

array([100, 100, 100, 100, 100,   5])

In [154]:
slice_of_arr[:] = 99

In [155]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [156]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

When we create an array using = from another array then, it doesnot create another arr, It just points to the same array.
<br>
And when we modify in either of them it reflects across both the array.
<br>
We need to create array from another using copy function wo create to overcome the above situation.

In [157]:
arr_copy = arr.copy()

In [158]:
arr_copy[0:8] = 88

In [159]:
arr_copy

array([88, 88, 88, 88, 88, 88, 88, 88,  8,  9, 10])

In [161]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

#### NumPy - Indexing and Selection - 2-D Array

In [165]:
arr_2d = np.array(np.arange(5,46,5)).reshape(3,3)

In [166]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [167]:
arr_2d[0]  # For accessing 1st row

array([ 5, 10, 15])

In [168]:
arr_2d[2][1]  #Accessing 1st element of 2nd row

40

In [169]:
arr_2d[2,1]   #Accessing 1st element of 2nd row

40

In [174]:
#matrix [rows ,columns ]
# Get all the rows till row-2 and all columns after 1 column
arr_2d[:2,1:]   

array([[10, 15],
       [25, 30]])

In [175]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

#### Conditional Selection

In [177]:
arr = np.arange(1,11)

In [178]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
bool_arr = arr > 5

In [184]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [185]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [187]:
arr_2d = np.arange(50).reshape(5,10)

In [188]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [191]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

#### NumPy Operations
1. Array with Array
2. .Array with Scalars
3. Universal Array Functions

In [193]:
arr = np.arange(0,11)

In [195]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [198]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [199]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [205]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [208]:
#Scala Operations
1/arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [203]:
print(arr + 100)
print(arr - 100)
print(arr * 100)
print(arr // 100)

[100 101 102 103 104 105 106 107 108 109 110]
[-100  -99  -98  -97  -96  -95  -94  -93  -92  -91  -90]
[   0  100  200  300  400  500  600  700  800  900 1000]
[0 0 0 0 0 0 0 0 0 0 0]


In [207]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [209]:
#Universal Array operations
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [210]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [212]:
arr.max()

10

In [218]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [219]:
arr.std()

3.1622776601683795